[network]
name: recurrent_model
input_dimension: 40
input: input_embedding
output: action

[fully_connected layer]
name: input_embedding
size: 64
logistic: tanh

[fully_connected layer]
input: input_embedding
name: state_prediction
logistic: linear
size: 40

[fully_connected layer]
input: input_embedding, state_prediction
name: action
logistic: tanh
size: 10

[fully_connected layer]
input: input_embedding, state_prediction
name: reward_prediction
logistic: sigmoid
size: 1
