[layer]
name: layer_a
type: feedforward
logistic: sigmoid
size: 16

[layer]
name: layer_b
input: layer_a, layer_c
logistic: sigmoid
type: recurrent
size: 16

[layer]
name: layer_c
input: layer_a, layer_b
logistic: tanh
type: recurrent
size: 4

[layer]
name: layer_d
input: layer_a, layer_b, layer_c
logistic: tanh
type: feedforward
size: 10

[network]
name: test
input_dimension: 4
input: layer_a
output: layer_d
